[".config/base16-shell"]
    type = "archive"
    url = "https://github.com/chriskempson/base16-shell/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["bin/fzf-key-bindings.fish"]
    type = "file"
    url = "https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish"
    refreshPeriod = "168h"
["bin/fzf-key-bindings.bash"]
    type = "file"
    url = "https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash"
    refreshPeriod = "168h"