# see <https://github.com/sxyazi/yazi/tree/shipped/yazi-config/preset> for defaults
[manager]
linemode = "mtime"
ratio = [1, 3, 4]
show_hidden = true

prepend_keymap = [
    { on = "k", run = "plugin --sync arrow --args=-1" },
    { on = "j", run = "plugin --sync arrow --args=1" },
]

[plugin]
# disable image preview
prepend_preloaders = [{ mime = "image/*", run = "noop" }]
prepend_previewers = [{ mime = "image/*", run = "noop" }]
